kind: pipeline
name: vuejs

steps:
  - name: check-vuejs
    image: node
    commands:
      - ./tests/vue-build.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
